"""empty message

Revision ID: 6bec0b548062
Revises: 
Create Date: 2017-03-03 15:28:26.962170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bec0b548062'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('reported_by', sa.String(length=20), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('incident_id'),
    sa.UniqueConstraint('latitude')
    )
    op.create_table('hydrant',
    sa.Column('hydrant_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('hydrant_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('hydrant_id')
    )
    op.create_table('stations',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('station_id'),
    sa.UniqueConstraint('latitude'),
    sa.UniqueConstraint('name')
    )
    op.create_table('truck',
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('truck_station', sa.String(length=100), nullable=True),
    sa.Column('parish', sa.String(length=50), nullable=True),
    sa.Column('addr', sa.String(length=200), nullable=True),
    sa.Column('truck_number', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('truck_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('truck')
    op.drop_table('stations')
    op.drop_table('hydrant')
    op.drop_table('alert')
    # ### end Alembic commands ###
